language: python
sudo: required
python:
    - '2.7'
install:
    - sudo useradd -g sudo -d /opt/stack -s /bin/bash -m stack
    - sudo -u stack cp devstack.conf /opt/stack
    - sudo -u stack cd /opt/stack
    - sudo -u stack git clone https://github.com/openstack-dev/devstack.git
    - sudo -u stack ls -la
    - sudo -u mv devstack.conf devstack/local.conf
    - sudo -u stack ./devstack/stack.sh
script: wget http://localhost:5000/
