language: python
python:
    - '2.7'
install:
    - git clone https://github.com/openstack-dev/devstack.git
    - mv devstack.conf devstack/local.conf
    - ./devstack/stack.sh
script: wget http://localhost:5000/
