language: python
sudo: required
python:
    - '2.7'
install:
    - sudo groupadd stack && sudo useradd -g stack -s /bin/bash -d /opt/stack -m stack && sudo echo "stack ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && sudo su stack
    - git clone https://github.com/openstack-dev/devstack.git
    - mv devstack.conf devstack/local.conf
    - ./devstack/stack.sh
script: wget http://localhost:5000/
