language: python
sudo: required
python:
    - '2.7'
install:
    - sudo groupadd stack
    - sudo useradd -g stack -s /bin/bash -d /opt/stack -m stack
    - sudo cat /etc/sudoers
    - sudo echo 'stack ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
    - su stack
    - cp devstack.conf /opt/stack
    - cd /opt/stack
    - git clone https://github.com/openstack-dev/devstack.git
    - ls -la
    - mv devstack.conf devstack/local.conf
    - ./devstack/stack.sh
script: wget http://localhost:5000/
